title: jxpiter
description: >-
  Cybersecurity enthusiast exploring reverse engineering, forensics, and system defense.
baseurl: "" # Leave empty if your site is deployed at the root
url: "https://jxpiter.github.io" # Change if different
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false

author: jxpiter
email: your.email@protonmail.com
