title: jxpiter
description: >-
  Cybersecurity enthusiast exploring reverse engineering, forensics, and system defense.
baseurl: "" # Leave empty if your site is deployed at the root
url: "https://jxpiter.github.io" # Change if different
theme: jekyll-theme-hacker
show_downloads: false

author: jxpiter
email: your.email@protonmail.com
