theme: minima

title: ""
author: Jxpiter
description: Cybersecurity portfolio, reverse engineering, and technical projects.

show_excerpts: true

header_pages:
  - index.md
  - about.md
  - contact.md
