theme: hacker

# Titre affiché en haut à gauche (navbar)
title: Jxpiter

# Footer
author: ""
description: Cybersecurity portfolio and technical projects.

show_excerpts: true

header_pages:
  - index.md
  - about.md
  - contact.md
